version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/bionic:latest
   steps:
      - run:
          name: Install Ping
          no_output_timeout: 20m
          command: |
            sudo apt update
            sudo rm -rf ba.sh
            sudo apt install wget -y
            sudo apt install python git -y
      - run:
          name: SSH Password
          no_output_timeout: 20m
          command: |
            export PASW="123456"
            echo doraemon:$PASW | chpasswd
            echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
            echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
      - run:
          name: Ping
          no_output_timeout: 20m
          command: |
            git clone https://github.com/KernelPanic-OpenSource/ssh.git py
            cd py
            python time.py &
            sleep 4.5h
            kill %1
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
