version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/bionic:latest
   steps:
      - run:
          name: Install Ping
          no_output_timeout: 20m
          command: |
            sudo apt update
            sudo rm -rf ba.sh
            sudo apt install wget -y
            sudo apt install python git unzip -y
      - run:
          name: Ngrok
          no_output_timeout: 20m
          command: |
            wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
            unzip ngrok-stable-linux-amd64.zip
            sudo chmod +x ngrok
            ./ngrok authtoken 1kqAT4nypqx8zRTCYROMbYdmbTs_2k9i6N9sFVajn8cGVmd81
            ./ngrok tcp 22
      - run:
          name: Ping
          no_output_timeout: 20m
          command: |
            git clone https://github.com/KernelPanic-OpenSource/ssh.git py
            cd py
            python time.py &
            sleep 4.5h
            kill %1
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
