version: 2.1
jobs:
  android:
   docker:
      - image: dopaemon/docker-image:android
   steps:
      - run:
          name: Install Ping
          no_output_timeout: 20m
          command: |
            sudo apt install iputils-ping -y
      - run:
          name: Ping
          no_output_timeout: 20m
          command: |
            ping www.google.com
workflows:
  version: 2.1
  cooking:
    jobs:
      - android
